### PR TITLE
Username and Password add in settings + Login

### PR DESCRIPTION
**Pull request by DewGew**
Added user and pass to settings. Only.
If username and password is not set in settings it will work like before,  if needed you have to login via domoticz  login.

@robgeerts add language strings:
language.settings.general.user_name = "user_name": "User name",
language.settings.general.user_name_help = "user_name_help": "Set domoticz user and password",
language.settings.general.pass_word = "pass_word": "Password",

more to add to language file:
language.settings.general.Login_to_Dashticz = "Login_to_Dashticz": "Dashticz Login",
language.settings.general.login = "login": "Login",
language.settings.logout = "logout": "Logout",
language.settings.general.loginEnabled = "loginEnabled": "Enable login",

### CODE REVIEW

**Comment by aalwash** [comment]
I already was thinking to build something similar, but stopped, because it's insecure.

The username/password are plaintext in the config, which is accessible by everyone.
The only way to fix this correctly, is this, to have a Basic auth (by HTTP) before you get into dashticz/domoticz

**Comment by DewGew** [comment]
dont set any user or pass then it will work as before. benefit to use this is ig you have several users with diffrent setups in domoticz. this is a better way the using http://user:pass@ipadress.com in domoticz_ip that is more exposed.

**Comment by robgeerts** [comment]
Great!
But, http://user:pass@ipadress.com wont work in some newer browsers... (because its insecure).
We have to figure out another way for this, but for now, this is a nice addition.
Will add the strings later today and merge this PR.

**Comment by aalwash** [comment]
As far as I can see in the code, the username and password are arguments in the URL, so not http://user:pass@ip

But http://ip/json.htm?username=<user>&password=<pass>
This works for all browsers

I've tried this before and Domoticz supports that

**Comment by DewGew** [comment]
Im working on a login also. Im testing it at the moment..

**Comment by DewGew** [comment]
dashticz_login
s
settings

**Comment by jsiegmund** [comment]
Can you help me out with some guidance on how to use this?

**Comment by DewGew** [comment]
Just add your domoticz username and password then enable Login (if you want a login) in settings or  add:
```
config['user_name'] = 'domoticz username';
config['pass_word'] = 'domoticz password';
config['loginEnabled'] = 1; /* Enable if you want a login form to dashticz */
```

**Comment by Disbury-Mockett** [comment]
just tried the login and noticed if i load folder/custom/config.js

it loads all my settings including user and password in clear text.

as when running it shows dashticz i can then work out where to go.

thus makes the login page redundant? or am i doing something wrong?

**Comment by aalwash** [comment]
Yup, that's the bad side of building these kind of things through the frontend :(

**Pull request merged**
