### PR TITLE
Fix for selector  Level Names (Base 64)

### PR DESCRIPTION
**Pull request by DewGew**
I dont know if this will work on erlier versions of domoticz (mine is 3.9540). Maybe someone can try this first?

### CODE REVIEW

**Comment by lokonli** [comment]
I tried. Doesn't work with my version of Domoticz: 3.8850

When was the change to base64 encoding of the selector Level Names?

**Comment by DewGew** [comment]
I think it has something to do with this Connor https://github.com/domoticz/domoticz/commit/16731807489d518b1134346242bb7c04db3d9dd0

**Comment by lokonli** [comment]
You're right.
Some more complaints on github:
https://github.com/domoticz/domoticz/issues/2454

What shall we do? 
Probably the old style levelnames contain the '|' character. We could test on that one. If it's found then it's not base64 encoded.

**Comment by lokonli** [comment]
This works for me:
         if (device['LevelNames'].includes('|'))  {
           names=device['LevelNames'].split('|');
         }
         else {
           names=window.atob(device['LevelNames']).split('|');
         }

**Comment by DewGew** [comment]
I can make a Domoticz version checker. If the user has version above 3.9476 encoding is true..

**Comment by DewGew** [comment]
merged #331

**Pull request merged**
