### PR TITLE
Fixed the spotify.js scope

### PR DESCRIPTION
**Pull request by Ectholian**
Please test and review, I think this way the plugins are less sensitive for global scope bugs like the getDevices function.

### CODE REVIEW

**Comment by robgeerts** [comment]
will test right away!

**Comment by robgeerts** [comment]
Squashed one bug... It called getLoginURL where it needed to call _getLoginURL

**Comment by Ectholian** [comment]
Darnit, i think i messed a file up. I fixed that already :)
The getracklist function has the same problem.

**Comment by Ectholian** [comment]
And the _getTracks too. Also, the last line of the module: }() has to be ended with a semicolon ;

**Comment by robgeerts** [comment]
ok, hold on

**Comment by robgeerts** [comment]
I think Im gonna try this plugin you mentioned: https://github.com/JMPerez/spotify-web-api-js

**Comment by Ectholian** [comment]
Might come in handy. Maybe my first quickfix is fine for the stable branch and for the beta this library might be good combined with this 'scoping' trick. I also see some javascript errors in the console when for example selecting a device without a playlist on it; this could potentially break the rest of javascript execution.

**Comment by robgeerts** [comment]
Ok, I will leave the original spotify.js in tact and work on another file while it is not finished ;)

**Pull request merged**
